// GENERATED FILE - do not edit by hand.
// Regenerate with: npm run gen
// Every level below was verified to have exactly one solution.
import { parseLevel } from "../core/level";
import type { Level } from "../core/types";

export const GENERATED_LEVELS: Level[] = [
  parseLevel("2-1", [
    "aAa.",
    "aa.a",
    "...A",
  ]),
  parseLevel("2-2", [
    "aA.",
    "a..",
    ".aA",
    ".aa",
  ]),
  parseLevel("2-3", [
    ".Aa",
    "aa.",
    ".aa",
    ".A.",
  ]),
  parseLevel("2-4", [
    "Aa.",
    "a.a",
    "aaA",
  ]),
  parseLevel("2-5", [
    ".Baa",
    "A2.a",
    ".baA",
    "b.bB",
    ".b..",
  ]),
  parseLevel("2-6", [
    "B2a..",
    ".abA.",
    ".ab..",
    "Aab..",
    "...bB",
  ]),
  parseLevel("2-7", [
    "...aa",
    "...Aa",
    "...Aa",
    "B..a.",
    "Bb...",
  ]),
  parseLevel("2-8", [
    "...aa",
    "...aa",
    "..abA",
    "bBAbB",
    ".bb..",
  ]),
  parseLevel("2-9", [
    ".aa2b",
    "A.baB",
    "..a2.",
    "BA2..",
    "bb...",
  ]),
  parseLevel("2-10", [
    ".ba.",
    "B22.",
    ".2ba",
    "b2.a",
    "ABA.",
  ]),
  parseLevel("2-11", [
    "bbbb.",
    "B...b",
    "...bb",
    "..B.A",
    "...aA",
  ]),
  parseLevel("2-12", [
    "..bbb",
    "A2B.b",
    "a..bB",
    ".a.Ab",
    ".aaaa",
  ]),
  parseLevel("2-13", [
    ".Bb.",
    "b.b.",
    "bbbb",
    "B..a",
    "..AA",
  ]),
  parseLevel("2-14", [
    "....B.",
    "..a.Ab",
    "B.2aa2",
    "bba2a2",
    "b..2b.",
    "..A...",
  ]),
  parseLevel("2-15", [
    ".AB...",
    "a2..a.",
    "b.aAba",
    "b..2a2",
    ".bb.a2",
    "....Bb",
  ]),
  parseLevel("2-16", [
    "...a2B",
    "...a2A",
    "aaa..b",
    "a..Ab.",
    ".aaB..",
  ]),
  parseLevel("2-17", [
    "a.abbB",
    "aa.aBA",
    "aaAaaa",
  ]),
  parseLevel("2-18", [
    "AA.bb.",
    "a.bB.b",
    ".bb.b.",
    "..bb.b",
    "....B.",
  ]),
  parseLevel("2-19", [
    "..ccc.",
    ".C...c",
    "....Ac",
    "Bb.2a2",
    "2a2bbc",
    "aAbBC.",
  ]),
  parseLevel("2-20", [
    "Bbb.cC",
    "...b22",
    ".cCcAb",
    "aa2ca2",
    ".aAaB.",
  ]),
  parseLevel("2-21", [
    "aa.aaC",
    "A.aB.2",
    "...b3c",
    "..b2AB",
    "C.2.b.",
    ".ccb..",
  ]),
  parseLevel("2-22", [
    ".ccC..",
    "2cA...",
    "a2...b",
    ".2c.bb",
    "CAabbB",
    ".a2B.b",
  ]),
  parseLevel("2-23", [
    "a.cc..",
    "AaCac.",
    "bbaaA2",
    "B.bBac",
    "bbb..c",
    ".b..Cc",
  ]),
  parseLevel("2-24", [
    ".C.Cc.",
    ".c.c..",
    "cc2a..",
    ".2b.a.",
    ".2bAB2",
    "A.Bb2b",
  ]),
];
