// ─────────────────────────────────────────────────────────────────────────────
// The roster. Twenty-five bosses, all original — no real people, no borrowed
// meme characters. The grammar is the joke: a grand title, a stupid epithet,
// and a fight that takes both completely seriously.
//
// Sim fields:    style · hp · poise · scale · speed · dmg · cooldown · moves ·
//                phases · gimmick
// Render fields: visual { body, build, head, weapon, extras, colours }
// Audio:         voice
// ─────────────────────────────────────────────────────────────────────────────

export const BOSSES = {
  // ══ THE POND ═══════════════════════════════════════════════════════════════
  duck: {
    name: 'THE DUCK', epithet: 'it has not blinked since tuesday.',
    style: 'duelist', hp: 520, poise: 70, scale: 1.55, speed: 3.3, dmg: 0.85, cooldown: [1.0, 1.9],
    moves: ['jab3', 'swipe', 'thrust', 'sweep'],
    phases: [{ at: 0.5, add: ['swipe2'], speed: 1.1, cd: 0.85, say: 'quack.' }],
    voice: 'duck',
    visual: { body: 'humanoid', build: 'lean', head: 'duck', weapon: 'halberd', extras: ['tabard'],
      skin: 0xe8e1cf, cloth: 0x3c4b37, trim: 0xe39b2c, accent: 0x2f6d8a },
  },
  grandpa: {
    name: 'GRANDPA BRICK', epithet: 'he has never explained the brick.',
    style: 'brute', hp: 600, poise: 95, scale: 1.72, speed: 2.4, dmg: 0.95, cooldown: [1.1, 2.0],
    moves: ['overhead', 'throw', 'swipe', 'stomp'],
    phases: [{ at: 0.5, add: ['throw3'], cd: 0.85, say: 'back in my day' }],
    gimmick: 'forgetful', voice: 'old',
    visual: { body: 'humanoid', build: 'heavy', head: 'grandpa', weapon: 'brick', extras: ['cardigan'],
      skin: 0xd8b095, cloth: 0x6b5a3e, trim: 0x9a3e2a, accent: 0x8f8f8f },
  },
  shrimp: {
    name: 'THE BIG SHRIMP', epithet: 'has seen things.',
    style: 'sweeper', hp: 580, poise: 80, scale: 1.75, speed: 3.0, dmg: 0.95, cooldown: [1.0, 1.8],
    moves: ['sweep', 'swipe2', 'leap', 'backflip', 'thrust'],
    phases: [{ at: 0.5, add: ['spin'], speed: 1.1, cd: 0.85 }],
    voice: 'shrimp',
    visual: { body: 'humanoid', build: 'long', head: 'shrimp', weapon: 'antennaWhip', extras: ['shell', 'tail'],
      skin: 0xf0876a, cloth: 0xd0643f, trim: 0xffd2b4, accent: 0x2a1c18 },
  },
  crab: {
    name: 'THE CRAB', epithet: 'everything becomes crab eventually.',
    style: 'crab', hp: 660, poise: 115, scale: 1.7, speed: 3.2, dmg: 1.0, cooldown: [1.0, 1.8],
    moves: ['pincer', 'clawSlam', 'scuttle', 'sweep'],
    phases: [{ at: 0.5, add: ['stomp'], speed: 1.15, cd: 0.85 }],
    voice: 'crab',
    visual: { body: 'humanoid', build: 'heavy', head: 'crab', weapon: 'claws', extras: ['shell'],
      skin: 0xc4452d, cloth: 0x7b2618, trim: 0xf3c4a2, accent: 0x1c1512 },
  },
  otherfrog: {
    name: 'THE OTHER FROG', epithet: 'he is also the main character.',
    style: 'mirror', hp: 820, poise: 55, scale: 1.0, radius: 0.45, height: 1.8, speed: 4.3, dmg: 1.0,
    cooldown: [0.45, 1.1],
    moves: ['mLight3', 'mHeavy', 'mRun'],
    phases: [{ at: 0.62, speed: 1.08, cd: 0.85, say: 'my turn.' }, { at: 0.3, speed: 1.1, cd: 0.75 }],
    gimmick: 'mirror', voice: 'frog', world: true,
    visual: { body: 'frog', variant: 'other', weapon: 'needle' },
    reward: { weapon: 'needle' },
  },

  // ══ THE COMMENT SECTION ════════════════════════════════════════════════════
  replyguy: {
    name: 'THE REPLY GUY', epithet: 'actually,',
    style: 'caster', hp: 700, poise: 75, scale: 1.55, speed: 3.4, dmg: 1.0, cooldown: [0.9, 1.7],
    moves: ['orbs', 'jab3', 'swipe', 'thrust'],
    phases: [{ at: 0.5, add: ['swipe2'], speed: 1.1, cd: 0.8, say: 'well, actually' }],
    voice: 'nasal',
    visual: { body: 'humanoid', build: 'lean', head: 'bubble', weapon: 'keyboard', extras: ['hoodie'],
      skin: 0xc7b8a6, cloth: 0x4b5566, trim: 0xf2f2f2, accent: 0x5aa0ff },
  },
  capslock: {
    name: 'THE CAPS LOCK', epithet: 'IS NOT YELLING.',
    style: 'brute', hp: 860, poise: 130, scale: 1.95, speed: 2.5, dmg: 1.05, cooldown: [1.1, 2.0],
    moves: ['shout', 'sweep', 'overhead', 'stomp'],
    phases: [{ at: 0.5, add: ['eruption'], cd: 0.85 }],
    gimmick: 'caps', voice: 'shout',
    visual: { body: 'humanoid', build: 'heavy', head: 'capskey', weapon: 'bigKey', extras: [],
      skin: 0x9a948c, cloth: 0x2c2c30, trim: 0xe8e4dc, accent: 0x7dff6a },
  },
  firstcomment: {
    name: 'THE FIRST COMMENT', epithet: 'first',
    style: 'hound', hp: 520, poise: 60, scale: 1.4, speed: 4.7, dmg: 0.95, cooldown: [0.55, 1.2],
    moves: ['thrust', 'jab3', 'swipe'],
    phases: [{ at: 0.5, add: ['swipe2'], speed: 1.15, cd: 0.8, say: 'second? no. FIRST' }],
    gimmick: 'first', voice: 'squeak', openingDelay: 0,
    visual: { body: 'humanoid', build: 'lean', head: 'ribbon', weapon: 'rapier', extras: ['cape'],
      skin: 0xd9c3a0, cloth: 0x1f3f8a, trim: 0xe0b646, accent: 0xffffff },
  },
  bot: {
    name: 'THE BOT', epithet: 'great post! check my profile.',
    style: 'duelist', hp: 780, poise: 85, scale: 1.6, speed: 3.2, dmg: 1.0, cooldown: [1.0, 1.8],
    moves: ['phantoms', 'swipe2', 'thrust', 'overhead'],
    phases: [{ at: 0.5, add: ['sweep'], cd: 0.8, say: 'great post!!' }],
    voice: 'robot',
    visual: { body: 'humanoid', build: 'normal', head: 'botcube', weapon: 'baton', extras: ['antenna'],
      skin: 0x9aa6ae, cloth: 0x3a4148, trim: 0x57e3ff, accent: 0xff5a8a },
  },
  moderator: {
    name: 'THE MODERATOR', epithet: 'the rules have changed.',
    style: 'sovereign', hp: 1450, poise: 150, scale: 2.1, speed: 3.0, dmg: 1.1, cooldown: [0.8, 1.6],
    moves: ['overhead', 'delayed', 'sweep', 'shout', 'leap', 'swipe2'],
    phases: [{ at: 0.66, add: ['stomp'], cd: 0.85 }, { at: 0.33, add: ['swipe3', 'eruption'], speed: 1.15, cd: 0.75 }],
    gimmick: 'moderator', voice: 'judge', world: true,
    visual: { body: 'humanoid', build: 'crowned', head: 'judge', weapon: 'gavel', extras: ['robe'],
      skin: 0xd8c6ae, cloth: 0x1a1a1f, trim: 0xe8e2d0, accent: 0xb89146 },
    reward: { weapon: 'banhammer' },
  },

  // ══ THE BACK OFFICE ════════════════════════════════════════════════════════
  monday: {
    name: 'THE MONDAY', epithet: 'again.',
    style: 'duelist', hp: 880, poise: 90, scale: 1.65, speed: 3.1, dmg: 1.0, cooldown: [1.3, 2.2],
    moves: ['swipe', 'overhead', 'thrust', 'sweep'],
    phases: [{ at: 0.5, add: ['swipe2'], cd: 0.9 }],
    gimmick: 'again', voice: 'groan',
    visual: { body: 'humanoid', build: 'normal', head: 'clock', weapon: 'clockhand', extras: ['tie'],
      skin: 0xcfc4b4, cloth: 0x3a4a5e, trim: 0xf4efe6, accent: 0xc0392b },
  },
  printer: {
    name: 'THE PRINTER', epithet: 'paper jam in tray 2.',
    style: 'brute', hp: 940, poise: 120, scale: 1.8, speed: 2.6, dmg: 1.05, cooldown: [1.0, 1.9],
    moves: ['volley', 'overhead', 'sweep', 'charge'],
    phases: [{ at: 0.5, add: ['stomp'], cd: 0.85 }],
    gimmick: 'jam', voice: 'machine',
    visual: { body: 'humanoid', build: 'heavy', head: 'printer', weapon: 'stapler', extras: [],
      skin: 0xe4e0d8, cloth: 0x5c5f66, trim: 0xf6f3ec, accent: 0x6fb3ff },
  },
  vacuum: {
    name: 'THE ROBOT VACUUM', epithet: 'it has a knife.',
    style: 'vacuum', hp: 880, poise: 200, scale: 1.0, radius: 1.15, height: 0.8, speed: 4.0, dmg: 1.0, cooldown: [0.8, 1.5],
    moves: ['bounce', 'knifeSpin', { id: 'charge', steps: [{ windup: .5, active: .9, recovery: .7, track: 7, trackActive: .6, advance: 0, charge: { speed: 15 }, hit: { shape: 'body', dmg: 20, knockdown: true, parryable: false }, sfx: 'charge' }] }],
    phases: [{ at: 0.5, speed: 1.15, cd: 0.8, say: 'resuming cleaning' }],
    gimmick: 'vacuum', voice: 'whirr',
    visual: { body: 'vacuum', skin: 0x2b2d31, cloth: 0x121316, trim: 0x57e3ff, accent: 0xc9d1d8 },
  },
  meeting: {
    name: 'THE MEETING', epithet: 'could have been an email.',
    style: 'sweeper', hp: 980, poise: 100, scale: 1.8, speed: 2.8, dmg: 1.05, cooldown: [1.0, 1.8],
    moves: ['sweep', 'overhead', 'swipe2', 'thrust'],
    phases: [{ at: 0.5, add: ['spin'], cd: 0.9, say: 'let\'s take this offline' }],
    gimmick: 'meeting', voice: 'drone',
    visual: { body: 'humanoid', build: 'long', head: 'projector', weapon: 'pointerStaff', extras: ['tie'],
      skin: 0xc8b9a4, cloth: 0x2d3440, trim: 0xf2eee4, accent: 0xff3b3b },
  },
  deadline: {
    name: 'THE DEADLINE', epithet: 'it was yesterday.',
    style: 'sovereign', hp: 1800, poise: 160, scale: 2.2, speed: 3.1, dmg: 1.12, cooldown: [0.8, 1.5],
    moves: ['leap', 'swipe2', 'overhead', 'delayed', 'charge', 'eruption'],
    phases: [{ at: 0.6, add: ['swipe3'], cd: 0.85 }, { at: 0.3, add: ['stomp'], speed: 1.15, cd: 0.72 }],
    gimmick: { id: 'deadline', seconds: 150 }, voice: 'tick', world: true,
    visual: { body: 'humanoid', build: 'crowned', head: 'hourglass', weapon: 'clockScythe', extras: ['robe'],
      skin: 0xbfae94, cloth: 0x201c18, trim: 0xe8d6a0, accent: 0xd9a441 },
    reward: { weapon: 'lance' },
  },

  // ══ THE 3 A.M. FEED ════════════════════════════════════════════════════════
  unskippable: {
    name: 'THE UNSKIPPABLE AD', epithet: 'skip in 5.',
    style: 'duelist', hp: 1000, poise: 95, scale: 1.7, speed: 3.2, dmg: 1.05, cooldown: [0.9, 1.7],
    moves: ['swipe2', 'thrust', 'overhead', 'volley'],
    phases: [{ at: 0.5, add: ['sweep'], cd: 0.85 }],
    gimmick: 'unskippable', voice: 'jingle',
    visual: { body: 'humanoid', build: 'normal', head: 'screenAd', weapon: 'skipSign', extras: [],
      skin: 0xbfb4a4, cloth: 0x22222a, trim: 0xffd23f, accent: 0xff3b6b },
  },
  influencer: {
    name: 'THE INFLUENCER', epithet: 'link in bio.',
    style: 'hound', hp: 960, poise: 80, scale: 1.6, speed: 4.2, dmg: 1.05, cooldown: [0.8, 1.5],
    moves: ['flash', 'jab3', 'thrust', 'swipe'],
    phases: [{ at: 0.5, add: ['swipe2'], speed: 1.1, cd: 0.85, say: 'smash that like' }],
    voice: 'bright',
    visual: { body: 'humanoid', build: 'lean', head: 'phoneRing', weapon: 'selfieStick', extras: [],
      skin: 0xe2c5a8, cloth: 0xf1e9dc, trim: 0xffffff, accent: 0xff7ac2 },
  },
  captcha: {
    name: 'THE CAPTCHA', epithet: 'select every square with a frog.',
    style: 'sweeper', hp: 1080, poise: 105, scale: 1.8, speed: 2.8, dmg: 1.05, cooldown: [1.0, 1.8],
    moves: ['tiles', 'sweep', 'overhead', 'swipe2'],
    phases: [{ at: 0.5, add: ['thrust'], cd: 0.85, say: 'please try again' }],
    voice: 'beep',
    visual: { body: 'humanoid', build: 'normal', head: 'captcha', weapon: 'checkmark', extras: [],
      skin: 0xd8d8d8, cloth: 0x2f3a4a, trim: 0xf5f5f5, accent: 0x3f8cff },
  },
  battery: {
    name: 'THE LOW BATTERY', epithet: '1%.',
    style: 'hound', hp: 1040, poise: 85, scale: 1.6, speed: 3.6, dmg: 1.05, cooldown: [0.9, 1.7],
    moves: ['swipe2', 'thrust', 'jab3', 'leap'],
    phases: [{ at: 0.5, add: ['sweep'], cd: 0.9 }],
    gimmick: 'battery', voice: 'lowbat',
    visual: { body: 'humanoid', build: 'lean', head: 'battery', weapon: 'cable', extras: [],
      skin: 0xa9a39a, cloth: 0x202226, trim: 0x46d160, accent: 0xff3b30 },
  },
  algorithm: {
    name: 'THE ALGORITHM', epithet: 'it already knows.',
    style: 'sovereign', hp: 2150, poise: 165, scale: 2.2, speed: 3.2, dmg: 1.15, cooldown: [0.7, 1.4],
    moves: ['swipe2', 'thrust', 'delayed', 'stance', 'stomp', 'orbs', 'leap'],
    phases: [{ at: 0.6, add: ['swipe3', 'orbRing'], cd: 0.85 }, { at: 0.3, add: ['eruption'], speed: 1.15, cd: 0.72 }],
    gimmick: 'algorithm', voice: 'choir', world: true,
    visual: { body: 'humanoid', build: 'crowned', head: 'eye', weapon: 'feedBlade', extras: ['robe', 'halo'],
      skin: 0xb9b2c8, cloth: 0x14121c, trim: 0xe8e0ff, accent: 0xc28bff },
    reward: { weapon: 'doomscroll' },
  },

  // ══ THE SERVER FARM ════════════════════════════════════════════════════════
  lag: {
    name: 'THE LAG', epithet: 'rubber-bands.',
    style: 'hound', hp: 1150, poise: 90, scale: 1.6, speed: 3.8, dmg: 1.1, cooldown: [0.8, 1.5],
    moves: ['thrust', 'swipe2', 'jab3', 'leap'],
    phases: [{ at: 0.5, add: ['swipe3'], speed: 1.1, cd: 0.85 }],
    gimmick: 'lag', voice: 'glitch',
    visual: { body: 'humanoid', build: 'lean', head: 'glitch', weapon: 'cable', extras: [],
      skin: 0x8a8f99, cloth: 0x15171b, trim: 0x57ffb0, accent: 0xff3bd4 },
  },
  hitbox: {
    name: 'THE HITBOX', epithet: 'you were nowhere near it.',
    style: 'brute', hp: 1280, poise: 150, scale: 2.0, speed: 2.5, dmg: 1.1, cooldown: [1.1, 2.0],
    moves: ['overhead', 'sweep', 'spin', 'stomp'],
    phases: [{ at: 0.5, add: ['shout'], cd: 0.85 }],
    gimmick: 'hitbox', voice: 'buzz',
    visual: { body: 'humanoid', build: 'heavy', head: 'wireframe', weapon: 'wireSword', extras: [], wire: true,
      skin: 0x46ff8a, cloth: 0x46ff8a, trim: 0x46ff8a, accent: 0xff4d4d },
  },
  patchnotes: {
    name: 'THE PATCH NOTES', epithet: 'nerfed: you.',
    style: 'duelist', hp: 1200, poise: 100, scale: 1.7, speed: 3.3, dmg: 1.1, cooldown: [0.9, 1.6],
    moves: ['swipe2', 'thrust', 'overhead', 'volley'],
    phases: [{ at: 0.66, add: ['swipe3'], cd: 0.9 }, { at: 0.33, add: ['leap'], speed: 1.1, cd: 0.8 }],
    gimmick: 'patch', voice: 'papery',
    visual: { body: 'humanoid', build: 'normal', head: 'scroll', weapon: 'redPen', extras: ['robe'],
      skin: 0xe8dcc0, cloth: 0x3a2e24, trim: 0xf6ecd4, accent: 0xd8342c },
  },
  loading: {
    name: 'THE LOADING SCREEN', epithet: 'tip: don\'t die.',
    style: 'sweeper', hp: 1220, poise: 110, scale: 1.8, speed: 2.9, dmg: 1.1, cooldown: [1.0, 1.8],
    moves: ['sweep', 'overhead', 'swipe', { id: 'eruption', weight: 1, cd: 7 }, { id: 'orbs', weight: 1, cd: 6 }],
    phases: [{ at: 0.5, add: ['swipe2'], cd: 0.85 }],
    gimmick: 'loading', voice: 'hum',
    visual: { body: 'humanoid', build: 'long', head: 'spinner', weapon: 'progressBar', extras: ['robe'],
      skin: 0xb8b8c0, cloth: 0x1b1d24, trim: 0xe0e6ff, accent: 0x57a8ff },
  },
  bluescreen: {
    name: 'THE BLUE SCREEN', epithet: 'a fatal exception has occurred.',
    style: 'sovereign', hp: 2700, poise: 170, scale: 2.35, speed: 3.2, dmg: 1.18, cooldown: [0.7, 1.4],
    moves: ['swipe2', 'overhead', 'leap', 'eruption', 'charge', 'delayed'],
    phases: [{ at: 0.65, add: ['swipe3', 'orbRing'], cd: 0.85 }, { at: 0.3, add: ['wipe', 'stomp'], speed: 1.12, cd: 0.7 }],
    gimmick: 'bluescreen', voice: 'error', world: true,
    visual: { body: 'humanoid', build: 'crowned', head: 'crt', weapon: 'powerMace', extras: ['robe'],
      skin: 0x9aa3b8, cloth: 0x0c1a4a, trim: 0xf0f4ff, accent: 0x1f5bff },
    reward: { ending: true },
  },
};

for (const [id, b] of Object.entries(BOSSES)) b.id = id;
